export enum STATUS {
    POWER_UP = 0x10,
    POWER_UP_WITH_BILL_IN_VALIDATOR = 0x11,
    POWER_UP_WITH_BILL_IN_STACKER = 0x12,
    INITIALIZE = 0x13,
    IDLING = 0x14,
    ACCEPTING = 0x15,
    STACKING = 0x17,
    RETURNING = 0x18,
    UNIT_DISABLED = 0x19,
    HOLDING = 0x1A,
    DEVICE_BUSY = 0x1B,
    REJECTING = 0x1C,
    DROP_CASSETTE_FULL = 0x41,
    DROP_CASSETTE_OUT_OF_POSITION = 0x42,
    VALIDATOR_JAMMED = 0x43,
    DROP_CASSETTE_JAMMED = 0x44,
    CHEATED = 0x45,
    PAUSE = 0x46,
    FAILED = 0x47,
    ESCROW_POSITION = 0x80,
    BILL_STACKED = 0x81,
    BILL_RETURNED = 0x82
}

export const STATUS_TEXT : {[key in STATUS]: string} = {
  [STATUS.POWER_UP]: 'Power up',
  [STATUS.POWER_UP_WITH_BILL_IN_VALIDATOR]: 'Power up with bill in validator',
  [STATUS.POWER_UP_WITH_BILL_IN_STACKER]: 'Power up with bill in stacker',
  [STATUS.INITIALIZE]: 'Initialize',
  [STATUS.IDLING]: 'Idling',
  [STATUS.ACCEPTING]: 'Accepting',
  [STATUS.STACKING]: 'Stacking',
  [STATUS.RETURNING]: 'Returning',
  [STATUS.UNIT_DISABLED]: 'Unit disabled',
  [STATUS.HOLDING]: 'Holding',
  [STATUS.DEVICE_BUSY]: 'Device busy',
  [STATUS.REJECTING]: 'Rejecting',
  [STATUS.DROP_CASSETTE_FULL]: 'Drop cassette full',
  [STATUS.DROP_CASSETTE_OUT_OF_POSITION]: 'Drop cassette out of position',
  [STATUS.VALIDATOR_JAMMED]: 'Validator jammed',
  [STATUS.DROP_CASSETTE_JAMMED]: 'Drop cassette jammed',
  [STATUS.CHEATED]: 'Cheated',
  [STATUS.PAUSE]: 'Pause',
  [STATUS.FAILED]: 'Failed',
  [STATUS.ESCROW_POSITION]: 'Bill in escrow position',
  [STATUS.BILL_STACKED]: 'Bill stacked',
  [STATUS.BILL_RETURNED]: 'Bill returned'

}
